/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./public/index.html'],
  theme: {
    extend: {
      colors: {
        tertiary: '#ffb786',
        outline: '#8c909f',
        'on-primary': '#002e6a',
        'on-surface-variant': '#c2c6d6',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'secondary-fixed': '#e2e2e2',
        surface: '#131313',
        'on-background': '#e5e2e1',
        'error-container': '#93000a',
        primary: '#adc6ff',
        'tertiary-fixed-dim': '#ffb786',
        'on-error': '#690005',
        'inverse-primary': '#005ac2',
        'tertiary-container': '#df7412',
        'on-primary-fixed-variant': '#004395',
        'inverse-on-surface': '#313030',
        'primary-fixed': '#d8e2ff',
        'on-tertiary-fixed-variant': '#723600',
        'on-secondary-fixed': '#1a1c1c',
        'surface-variant': '#353534',
        'surface-bright': '#393939',
        'primary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#311400',
        'outline-variant': '#424754',
        'on-secondary': '#2f3131',
        'surface-dim': '#131313',
        'on-secondary-fixed-variant': '#454747',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-container': '#b4b5b5',
        'primary-container': '#4d8eff',
        error: '#ffb4ab',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'on-tertiary': '#502400',
        'secondary-container': '#454747',
        'surface-tint': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e1',
        'on-surface': '#e5e2e1',
        background: '#131313',
        'secondary-fixed-dim': '#c6c6c7',
        'on-primary-container': '#00285d',
        secondary: '#c6c6c7',
        'tertiary-fixed': '#ffdcc6',
        'on-tertiary-container': '#461f00',
        'brand-electric': '#3B82F6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'section-padding-desktop': '120px',
        unit: '8px',
        'section-padding-mobile': '64px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'code-sm': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'label-caps': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '300' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'code-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '300' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
